# =============================================================================
# 02_pseudobulk_de.R — Pseudobulk Differential Expression & GO (Part 2)
# =============================================================================
# Requires: pbmc_harmony_curated.rds generated by 01_single_cell.R
# Covers pseudobulk DE (DESeq2), volcano plots, GO enrichment,
#         log2FC heatmaps, and network inference.
# =============================================================================

# ── Configuration (must match 01_single_cell.R) ───────────────────────────────
PIPELINE_DIR <- "~/projects2/eleo/ScRNA/metodologia/ScRNASeq-Docker/"
DATA_DIR     <- "~/projects2/eleo/ScRNA/"
base_dir     <- file.path(DATA_DIR, "metodologia/resultados")

source(file.path(PIPELINE_DIR, "load_libraries.R"))
source(file.path(PIPELINE_DIR, "custom_seurat.R"))
source(file.path(PIPELINE_DIR, "ScRNA_Analysis_Functions.R"))

list2env(create_pipeline_dirs(base_dir), envir = .GlobalEnv)  # creates output folders and loads their paths as variables

# ── Load checkpoint from Part 1 ───────────────────────────────────────────────
pbmc_harmony <- readRDS(file.path(dir_objects, "pbmc_harmony_curated.rds"))

# ████████████████████████  PART 2 — PSEUDOBULK DE & GO  ██████████████████████
# =============================================================================


# =============================================================================
# SECTION 14 — CELL-TYPE SUBSETS
# =============================================================================
# Creates one Seurat subset per curated cell type for downstream pseudobulk
# analysis. Object names are sanitised so they can be used safely as list names
# and output filenames.
#
# ┌─ SET THE ANNOTATION COLUMN TO USE FOR PART 2 ───────────────────────────────
#   pseudobulk_annot_col : metadata column containing the final cell-type labels
# └─────────────────────────────────────────────────────────────────────────────
pseudobulk_annot_col <- "celltype_curated"

output_dir <- dir_09

# Create cell-type subsets for pseudobulk analysis
cell_type_subsets <- create_cell_type_subsets(pbmc_harmony, annot_col = pseudobulk_annot_col)


# =============================================================================
# SECTION 15 — PSEUDO-REPLICATE ASSIGNMENT
# =============================================================================
# Assigns random pseudo-replicates within each condition for every cell type.
# Only subsets containing at least two conditions are kept for Part 2.
#
# ┌─ PSEUDOBULK PARAMETERS ──────────────────────────────────────────────────────
#   pseudobulk_conditions : optional condition subset to retain (NULL = all)
#                           Examples:
#                             NULL              → use all conditions (0N, 0.5N, 5N)
#                             c("0N", "0.5N")   → use only 0N and 0.5N
#                             "5N"              → use only 5N
#   n_pseudoreps          : number of pseudo-replicates per condition (per cell type)
# └─────────────────────────────────────────────────────────────────────────────

# Use all conditions
#pseudobulk_conditions <- NULL
# Uncomment below to use only specific conditions:
# pseudobulk_conditions <- c("0N", "0.5N")      # Compare control vs low nitrogen
#pseudobulk_conditions <- c("0.5N", "5N")      # Compare nitrogen treatments
# pseudobulk_conditions <- "5N"                  # Single condition (rarely useful)

n_pseudoreps <- 3

output_dir <- dir_09

# Assign pseudo-replicates (uses global random seed set in INITIALIZATION)
cell_type_subsets_replicates <- assign_pseudoreplicates_batch(cell_type_subsets,
                                                             pseudobulk_conditions = pseudobulk_conditions,
                                                             n_pseudoreps = n_pseudoreps)


# Example QC checks for one subset:
table(cell_type_subsets_replicates$Pavement_Cell$replicate)
table(cell_type_subsets_replicates$Pavement_Cell$orig.ident)


# =============================================================================
# SECTION 16 — PSEUDOBULK TABLES AND DESEQ2
# =============================================================================
# Aggregates counts by pseudo-replicate for each cell type, saves the resulting
# count tables, and runs DESeq2 for the user-defined pairwise contrasts.
#
# ┌─ DEFINE YOUR CONDITION CONTRASTS HERE ──────────────────────────────────────
#   comparaciones : each entry must contain
#                   conds = c("reference", "treatment")
#                   tag   = output folder / file label
# └─────────────────────────────────────────────────────────────────────────────
comparaciones <- list(
  list(conds = c("0.5N", "5N"), tag = "0.5N_vs_5N"),
  list(conds = c("0N",   "5N"), tag = "0N_vs_5N")
)

output_dir <- dir_10

# ┌─ SELECT WHICH CELL TYPES TO ANALYZE ────────────────────────────────────────
#   NULL = analyze all cell types
#   c("Epidermis", "Cortex") = analyze only these
# └─────────────────────────────────────────────────────────────────────────────
cell_types_to_analyze <- NULL  # Change to c("Epidermis", "Cortex") to filter

# Run pseudobulk aggregation and DESeq2 analysis
deseq2_results <- run_pseudobulk_deseq2_analysis(
  cell_type_subsets_replicates = cell_type_subsets_replicates,
  comparisons = comparaciones,
  output_dir = output_dir,
  cell_types = cell_types_to_analyze,
  pseudobulk_dir = file.path(dir_09, "pseudobulk_replicas")
)


# =============================================================================
# SECTION 17 — VOLCANO PLOTS
# =============================================================================
# Renders one PNG volcano plot per cell type for a selected contrast and also
# combines them into a single PDF.
#
# ┌─ VOLCANO PARAMETERS ─────────────────────────────────────────────────────────
#   volcano_tag : tag of the contrast to visualize (must match comparaciones)
#   padj_cut    : adjusted p-value threshold
#   lfc_cut     : absolute log2 fold-change threshold
# └─────────────────────────────────────────────────────────────────────────────
volcano_tag <- "0.5N_vs_5N"
padj_cut    <- 0.05
lfc_cut     <- 1

output_dir <- dir_11

render_volcano_plots(
  results_dir = file.path(dir_10, volcano_tag),
  output_dir  = file.path(dir_11, volcano_tag),
  pdf_name    = paste0("VolcanoPlots_", volcano_tag, ".pdf"),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut
)


# =============================================================================
# SECTION 18 — DIFFERENTIAL GENE TABLES
# =============================================================================
# Builds combined differential-expression summary tables for one selected
# contrast across all cell types.
#
# ┌─ DIFFERENTIAL TABLE PARAMETERS ──────────────────────────────────────────────
#   diff_tag    : tag of the contrast to summarize
#   diff_prefix : output filename prefix for the discrete matrix
# └─────────────────────────────────────────────────────────────────────────────
diff_tag    <- volcano_tag
diff_prefix <- paste0("tabla_diferenciales_", diff_tag)

output_dir <- dir_12

diff_tables <- build_differential_tables(
  results_dir = file.path(dir_10, diff_tag),
  output_dir  = file.path(dir_12, diff_tag),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  prefix      = diff_prefix
)


# =============================================================================
# SECTION 19 — GO ENRICHMENT (SIMPLE)
# =============================================================================
# Gene Ontology enrichment per cell type for the selected contrast.

go_space    <- "BP"          # Change to "MF" or "CC" if desired
padj_cutoff <- 0.05

deseq2_files <- list.files(file.path(dir_10, diff_tag),
                           pattern = "^DESeq2_.*\\.csv$",
                           full.names = TRUE)

for (deseq2_file in deseq2_files) {
  cell_type <- gsub("^DESeq2_|\\.csv$", "", basename(deseq2_file))

  deseq2_results <- read.csv(deseq2_file, row.names = 1)
  sig_genes <- rownames(deseq2_results)[deseq2_results$padj < padj_cutoff]

  if (length(sig_genes) > 0) {
    run_simple_go_enrichment(
      diff_table = data.frame(gene_id = sig_genes),
      output_dir = file.path(dir_13, diff_tag),
      orgdb = org.At.tair.db,
      keytype = "TAIR",
      go_space = go_space,
      padj_cutoff = padj_cutoff,
      cell_type = cell_type,
      contrast_tag = diff_tag
    )
  }
}

# =============================================================================
# SECTION 20 — LOG2FC HEATMAP + CLUSTERING
# =============================================================================
# Heatmap of log2FC values across all cell types for the selected contrast.
#
# ┌─ PARAMETERS ─────────────────────────────────────────────────────────────────
#   CLUSTER_METHOD : "hclust" — hierarchical (euclidean + complete + cutreeDynamic)
#                    "wgcna"  — coexpression network (TOM + mergeCloseModules)
#   heatmap_limits : color scale range
#   wgcna_merge_cut: merge WGCNA modules with correlation > (1 - wgcna_merge_cut)
# └─────────────────────────────────────────────────────────────────────────────
CLUSTER_METHOD  <- "wgcna"   # "hclust" or "wgcna"
heatmap_limits  <- c(-5, 5)
wgcna_merge_cut <- 0.25

heatmap_results <- build_logfc_heatmap(
  logfc_table  = diff_tables$logfc,
  contrast_tag = diff_tag,
  output_dir   = file.path(dir_12, diff_tag),
  method       = CLUSTER_METHOD,
  limits       = heatmap_limits,
  merge_cut    = wgcna_merge_cut
)


# =============================================================================
# SECTION 21 — GO ENRICHMENT PER CLUSTER
# =============================================================================
# Runs GO enrichment for each cluster identified in Section 20.
# Uses the cluster assignments from heatmap_results.

go_clusters_padj <- 0.05

for (clust_id in unique(heatmap_results$cluster)) {
  genes <- heatmap_results$gene_id[heatmap_results$cluster == clust_id]

  run_simple_go_enrichment(
    diff_table   = data.frame(gene_id = genes),
    output_dir   = file.path(dir_12, diff_tag, paste0("GO_clusters_", CLUSTER_METHOD)),
    orgdb        = org.At.tair.db,
    keytype      = "TAIR",
    go_space     = "BP",
    padj_cutoff  = go_clusters_padj,
    cell_type    = as.character(clust_id),
    contrast_tag = diff_tag
  )
}


# =============================================================================
# SECTION 22 — NETWORK INFERENCE PER CLUSTER (3-METHOD MIX STRATEGY)
# =============================================================================
# THREE COMPLEMENTARY network inference analyses per cluster from Section 20:
# (Analogous to Sección 20's dual-clustering strategy: hclust vs WGCNA)
#
# ┌─ THE MIX STRATEGY ────────────────────────────────────────────────────────────
#   We do NOT choose between GENIE3, WGCNA, and SYNERGY. Instead, we run all 3
#   because they answer different questions:
#
#   • GENIE3 (directed, like hclust geometry):
#       Finds TF → target edges with predictive power.
#       Filter: Pearson |r| ≥ 0.90 (avoids noise via correlation).
#       ✓ Strength: directionality, interpretable as causality.
#       ⚠ Weakness: only TFs regulate; less robust to outliers.
#
#   • WGCNA (undirected, like WGCNA coexpression):
#       Finds coexpressed gene pairs via TOM (Topological Overlap).
#       Filter: TOM ≥ 0.15 (genes that share ≥15% of neighbors).
#       ✓ Strength: coexpression robustness; ANY gene can regulate ANY gene.
#       ⚠ Weakness: no directionality; local structure matters, not global.
#
#   • SYNERGY (mix, high-confidence):
#       Combines GENIE3 directionality + WGCNA coexpression validation.
#       Filter: Pearson ≥0.90 AND TOM ≥0.15 (both layers must pass).
#       Score: geometric mean of rank-normalized GENIE3 × TOM.
#       ✓ Strength: high-confidence TF→target edges backed by coexpression.
#       ⚠ Weakness: very restrictive; fewer edges (top tier only).
#
# ┌─ WHAT IS TOM? (Topological Overlap Matrix) ──────────────────────────────────
#   TOM measures "robustness" of a gene pair's connection by counting shared
#   neighbors: if gene A and gene B both correlate with genes {C, D, E, ...},
#   they are truly connected, not by chance.
#
#   Formula:   TOM(A,B) = (# shared neighbors) / min(neighbors(A), neighbors(B))
#   Range:     0 to 1 (0 = no shared neighbors, 1 = identical neighborhoods)
#   Severity:  TOM ≥ 0.25 is "strict", 0.15 is "moderate", 0.08 is "loose"
#   Your threshold (0.15) = top 5% of edge confidences = MODERATE
#
# Both functions read pseudobulk replicate counts from Section 16, normalize
# (CPM + log2) and run independently. Outputs are saved in dir_14/<contrast>/.
#
# ┌─ COMMON PARAMETERS ──────────────────────────────────────────────────────────
#   n_top_clusters : how many largest clusters to analyze
#   min_var_filter : drop genes with variance below this across samples
# ├─ GENIE3 PARAMETERS ──────────────────────────────────────────────────────────
#   net_orgdb      : Bioconductor OrgDb (e.g. org.At.tair.db, org.Hs.eg.db)
#   net_keytype    : key type matching gene IDs (e.g. "TAIR", "ENSEMBL")
#   custom_tfs     : optional vector of TF IDs to override GO-based detection
#   cor_min        : Pearson |r| correlation threshold (≥0.90 = MODERATE)
#   genie3_ntrees  : Random Forest trees (more = stabler, slower)
#   n_cores        : parallel cores for GENIE3
# ├─ WGCNA PARAMETERS ───────────────────────────────────────────────────────────
#   soft_power     : power for adjacency (default 6; higher = fewer edges)
#   network_type   : "signed" (correlation direction matters) or "unsigned"
#   tom_threshold  : TOM threshold (≥0.15 = MODERATE, equivalent to Pearson 0.90)
# └─────────────────────────────────────────────────────────────────────────────
# ┌─ CHOOSE WHICH METHODS TO RUN ────────────────────────────────────────────────
#   Edit the line below to run only desired methods. Options:
#   c("GENIE3", "WGCNA", "SYNERGY")  — run all 3
#   c("GENIE3", "SYNERGY")            — skip WGCNA
#   c("SYNERGY")                      — only high-confidence
#   c("GENIE3", "WGCNA")             — skip SYNERGY
# └─────────────────────────────────────────────────────────────────────────────
network_methods <- c("GENIE3", "WGCNA", "SYNERGY")  # CHANGE AS NEEDED

# ── Common parameters ────────────────────────────────────────────────────────
n_top_clusters <- 3
min_var_filter <- 0.01

# GENIE3 parameters
net_orgdb     <- org.At.tair.db
net_keytype   <- "TAIR"
custom_tfs    <- NULL
cor_min       <- 0.75        # EXPLORATORY — top 15% (Pearson |r| >= 0.75)
genie3_ntrees <- 100
n_cores       <- 4

# WGCNA parameters
soft_power    <- 6
network_type  <- "signed"
tom_threshold <- 0.05        # EXPLORATORY — top 15% (TOM >= 0.05)

# ── Run all selected methods in one call ─────────────────────────────────────
net_pipeline <- run_network_inference_pipeline(
  heatmap_results      = heatmap_results,
  pseudobulk_dir       = file.path(dir_09, "pseudobulk_replicas"),
  output_base_dir      = file.path(dir_14, diff_tag),
  methods              = network_methods,
  orgdb                = net_orgdb,
  keytype              = net_keytype,
  custom_tfs           = custom_tfs,
  cor_min              = cor_min,
  genie3_ntrees        = genie3_ntrees,
  n_cores              = n_cores,
  soft_power           = soft_power,
  network_type         = network_type,
  tom_threshold        = tom_threshold,
  n_top_clusters       = n_top_clusters,
  min_var_filter       = min_var_filter
)

# ── Extract results for downstream sections ─────────────────────────────────
genie3_results  <- net_pipeline$results$GENIE3
wgcna_results   <- net_pipeline$results$WGCNA
synergy_results <- net_pipeline$results$SYNERGY


# =============================================================================
# SECTION 22B — THRESHOLD TESTING (OPTIONAL)
# =============================================================================
# Test 5 different threshold combinations to find optimal settings.
# Generates PDF comparing edge counts and cluster coverage.
#
# ┌─ UNCOMMENT TO RUN ────────────────────────────────────────────────────────
#   Set RUN_THRESHOLD_TEST <- TRUE below to execute
# └─────────────────────────────────────────────────────────────────────────────

RUN_THRESHOLD_TEST <- FALSE  # Set to TRUE to run threshold exploration

if (RUN_THRESHOLD_TEST) {
  message("\n🔬 TESTING NETWORK THRESHOLDS (5 combinations)...")

  threshold_test <- test_network_thresholds(
    heatmap_results = heatmap_results,
    pseudobulk_dir  = file.path(dir_09, "pseudobulk_replicas"),
    output_dir      = file.path(dir_14, diff_tag, "THRESHOLD_TEST"),
    method          = "SYNERGY",  # Change to "GENIE3" or "WGCNA" if desired
    orgdb           = net_orgdb,
    keytype         = net_keytype,
    custom_tfs      = custom_tfs,
    genie3_ntrees   = genie3_ntrees,
    n_cores         = n_cores,
    soft_power      = soft_power,
    network_type    = network_type,
    n_top_clusters  = n_top_clusters,
    min_var_filter  = min_var_filter
  )

  message("\n✓ Threshold test complete.")
  message("  PDF: ", threshold_test$pdf)
  message("  Recommendation: ", threshold_test$recommendation)
}


# =============================================================================
# SECTION 23 — NETWORK VISUALIZATION (FORCE-DIRECTED LAYOUT)
# =============================================================================
# Clean network visualization using force-directed (Fruchterman-Reingold) layout.
# Choose ONE method below; visualizes all filtered edges with igraph.
#
# ┌─ CHOOSE METHOD ─────────────────────────────────────────────────────────────
#   Selected method will be visualized in detail (force-directed, node sizes by
#   degree, edge widths by weight). This complements SEC 22's PDF summaries.
#
#   Recommendations:
#   • GENIE3  → see TF directionality visually
#   • WGCNA   → see coexpression structure and modules
#   • SYNERGY → highest confidence edges (TF→target validated by coexpression)
# └─────────────────────────────────────────────────────────────────────────────

viz_method <- "SYNERGY"   # "GENIE3", "WGCNA", or "SYNERGY"

viz_results <- switch(viz_method,
  "GENIE3"  = genie3_results,
  "WGCNA"   = wgcna_results,
  "SYNERGY" = synergy_results,
  synergy_results  # default to SYNERGY
)

viz_weight_col <- switch(viz_method,
  "GENIE3"  = "weight",
  "WGCNA"   = "TOM",
  "SYNERGY" = "score_synergy",
  "score_synergy"
)

viz_directed <- switch(viz_method,
  "GENIE3"  = TRUE,
  "WGCNA"   = FALSE,
  "SYNERGY" = TRUE,
  TRUE
)

viz_edge_color <- switch(viz_method,
  "GENIE3"  = "#2ca02c",   # green
  "WGCNA"   = "#1f77b4",   # blue
  "SYNERGY" = "#d62728",   # red
  "#1f77b4"
)

visualize_network_per_cluster(
  network_results     = viz_results,
  cluster_assignments = heatmap_results,
  output_dir          = file.path(dir_14, diff_tag, "VISUALIZATION"),
  method_name         = viz_method,
  weight_col          = viz_weight_col,
  directed            = viz_directed,
  edge_color          = viz_edge_color
)

message("\n✓ SECTION 23 COMPLETE: Network visualization saved")


# =============================================================================
# SECTION 24 — CLUSTER PROFILE REPORTS
# =============================================================================
# Per-cluster profiles: heatmaps, expression statistics, functional annotation.
#
# For each cluster from SEC 20:
#   • Expression heatmap (pseudobulk × genes, with row clustering)
#   • Expression statistics (mean, SD, range)
#   • Gene count and composition
#
# Links to GO enrichment results from SEC 21 for functional context.

exprMatr_pseudobulk <- load_pseudobulk_matrix(
  file.path(dir_09, "pseudobulk_replicas"),
  normalize = TRUE
)

generate_cluster_profile_report(
  cluster_assignments = heatmap_results,
  pseudobulk_matrix   = exprMatr_pseudobulk,
  output_dir          = file.path(dir_12, diff_tag, "CLUSTER_PROFILES"),
  method_name         = "WGCNA"  # clustering method used in SEC 20
)

message("\n✓ SECTION 24 COMPLETE: Cluster profiles saved")



