"""
03_pseudotime.py — Pseudotime Analysis
======================================
Pseudotime analysis on the AnnData object exported from the R pipeline.

Requires:
    scanpy, scFates, palantir, matplotlib, seaborn, pandas, numpy

Input:
    pbmc_harmony_curated.h5ad  (generated by 01_single_cell.R via export_to_scanpy())

Usage:
    python3 03_pseudotime.py
    # or inside the Docker container:
    docker exec -it r45 bash -c "source /opt/venv/bin/activate && python3 /workspace/workflow/03_pseudotime.py"
"""

import os
import sys
import warnings
warnings.filterwarnings("ignore")

# Data manipulation and numerical computation
import numpy as np
import pandas as pd
from scipy.stats import pearsonr
from sklearn.preprocessing import scale
from sklearn.metrics import pairwise_distances_argmin

# Single-cell analysis
import scanpy as sc
import scFates as scf
import palantir

# Visualization
import matplotlib
matplotlib.use("Agg")  # Backend no interactivo (para servidor/Docker)
import matplotlib.pyplot as plt
import seaborn as sns

# Settings
sc.settings.verbosity = 3
sc.settings.logfile = sys.stdout

# ─────────────────────────────────────────────
# FUNCTIONS
# ─────────────────────────────────────────────

def scfates_trajectories_alignment2(nombre, adata, clusters, root_cluster, nodes, sigma, eigen, seeed, plambda):
    """
    Builds a trajectory using scFates + Palantir + ElPiGraph
    on a subset of cells defined by their grouped annotations.
    """

    # --------------------------
    # 1. Subset by clusters
    # --------------------------
    if clusters is None or len(clusters) == 0:
        adata = adata.copy()
    elif len(clusters) == 1:
        adata = adata[adata.obs['annotation_curada_esp'] == clusters[0]].copy()  # noqa
    else:
        adata = adata[adata.obs['annotation_curada_esp'].isin(clusters)].copy()

    sc.pp.neighbors(adata)
    sc.tl.leiden(adata, resolution=0.5)

    # --------------------------
    # 2. Palantir → Diffusion Maps
    # --------------------------
    pca_projections = pd.DataFrame(adata.obsm["X_pca"], index=adata.obs_names)
    dm_res = palantir.utils.run_diffusion_maps(pca_projections, n_components=50)
    ms_data = palantir.utils.determine_multiscale_space(dm_res, n_eigs=eigen)

    adata.obsm["X_palantir"] = ms_data.values

    # --------------------------
    # 3. Neighborhoods + ForceAtlas2
    # --------------------------
    sc.pp.neighbors(adata, n_neighbors=50, use_rep="X_palantir", method='umap')
    adata.obsm["X_pca2d"] = adata.obsm["X_pca"][:, :2]
    sc.tl.draw_graph(adata, init_pos='X_pca2d')

    title = f"{nombre}_{nodes}_nodes_{sigma}_sigma_{eigen}_eigen_{plambda}_lambda"
    sc.set_figure_params(figsize=(10, 10), dpi=100, dpi_save=100)

    # Visualization 1
    sc.pl.draw_graph(
        adata,
        color=['annotation_curada_esp'],
        add_outline=True,
        legend_fontsize=10, legend_fontoutline=2, size=50,
        title="ESP_FA_clusters",
        palette=sns.color_palette('colorblind'),
        save=f"ESP_FA_clusters.png"
    )

    # Visualization 2 (comentada — descomentár si se necesita)
    # sc.pl.draw_graph(
    #     adata,
    #     color=['annotation_chinos_uni'],
    #     add_outline=True,
    #     legend_fontsize=10, legend_fontoutline=2, size=50,
    #     title="CN_FA_clusters",
    #     palette=sns.color_palette('colorblind'),
    #     save=f"CN_FA_clusters2.png"
    # )

    # --------------------------
    # 4. ElPiGraph with scFates
    # --------------------------
    scf.tl.tree(
        adata,
        method="ppt",
        Nodes=nodes,
        use_rep="palantir",
        plot=False,
        device="cpu",
        seed=seeed,
        ppt_lambda=plambda,
        ppt_nsteps=200,
        ppt_sigma=sigma
    )

    scf.pl.graph(
        adata,
        title=title,
        color_cells='annotation_curada_esp',
        palette=sns.color_palette('colorblind'),
        save=f"_{title}_NODES_FA_diffusion_trajectory_clusters.png"
    )

    # --------------------------
    # 5. Select root cell
    # --------------------------
    mask = (adata.obs['annotation_curada_esp'] == root_cluster).to_numpy()
    cluster_cells = adata.obs_names[mask]

    sub_conn = adata.obsp['connectivities'][mask][:, mask]
    degrees = np.array(sub_conn.sum(axis=1)).flatten()

    root_cell = cluster_cells[degrees.argmax()]
    print("Representative cell:", root_cell)

    cell_id = root_cell

    # Highlight root cell in graph
    adata.obs["highlight"] = adata.obs_names.isin([cell_id])
    adata_sorted = adata[adata.obs.sort_values("highlight").index, :]

    sc.pl.draw_graph(
        adata_sorted,
        color="highlight",
        palette=["lightgray", "red"],
        size=20,
        title=f"Root cell: {cell_id}",
        frameon=False
    )

    # Mark root and compute pseudotime
    adata.obs["is_root"] = adata.obs_names == root_cell
    scf.tl.root(adata, root="is_root")

    # --------------------------
    # 6. Pseudotime
    # --------------------------
    scf.tl.pseudotime(adata)

    # Export pseudotime per cell
    cell_time = adata.obs[["t"]].copy()
    cell_time.index.name = "cell_id"

    if "annotation_curada_esp" in adata.obs.columns:
        cell_time["cell_type"] = adata.obs["annotation_curada_esp"]

    out_file = f"{nombre}_pseudotime_per_cell.tsv"
    cell_time.to_csv(out_file, sep="\t")
    print(f"Pseudotime exported to {out_file}")

    # --------------------------
    # 7. Trajectory colored by pseudotime
    # --------------------------
    scf.pl.trajectory(
        adata,
        color_seg="t",
        basis="draw_graph_fa",
        frameon=False,
        s=50,
        scale_path=0.6,
        save=f"_{title}_pseudotime.png"
    )

    sc.pl.umap(adata, color="leiden")

    return adata


def scfates_trajectories_dendogram(adata):
    """
    Generates pseudotime, dendrogram, and segmented trajectory.
    Requires scf.tl.tree() to have been run first.
    """

    if "seg" not in adata.obs:
        raise ValueError("ERROR: adata.obs['seg'] not found. Run scf.tl.tree() first.")

    # -------------------------------
    # 1. Graph colored by milestones
    # -------------------------------
    sc.pl.draw_graph(
        adata,
        color=["milestones", "leiden"],
        palette=sns.color_palette("colorblind"),
        add_outline=True,
        legend_fontsize=10,
        legend_fontoutline=2
    )

    # -------------------------------
    # 2. scFates dendrogram
    # -------------------------------
    scf.tl.dendrogram(adata)

    scf.pl.dendrogram(
        adata,
        color="seg",
        palette=sns.color_palette("colorblind"),
        legend_fontoutline=True,
        legend_loc="on data",
        save="_seg.pdf"
    )

    scf.pl.dendrogram(
        adata,
        color="milestones",
        palette=sns.color_palette("colorblind"),
        legend_fontoutline=True,
        legend_loc="on data",
        save="_milestones.pdf"
    )

    print("Dendrogram generated")

    return adata


# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

INPUT_H5AD      = "/home/mvergara/projects2/eleo/ScRNA/metodologia/resultados/08_export/pbmc_harmony_curated.h5ad"  # output of 01_single_cell.R
BASE_DIR        = "/home/mvergara/projects2/eleo/ScRNA/results/pseudotime"
ROOT_CELL_TYPE  = "Stomatal lineage"               # root cell type for the tree (adjust as needed)
ANNOTATION_COL  = "celltype_curated"               # annotation column exported from R (must match dest_col in Section 12)
N_NEIGHBORS     = 30                               # k-neighbors for the graph
N_PCS           = 30                               # PCs to use
RANDOM_SEED     = 1807

# ── Cell type subset ─────────────────────────────────────────
# Set None to use ALL cells, or a list of cell types to subset.
# Names must match exactly the values in ANNOTATION_COL.
#
# Example 1 — stomatal lineage:
#   CELL_TYPES_SUBSET = ["Stomatal lineage", "Pavement cell", "Guard cell"]
#
# Example 2 — vascular only:
#   CELL_TYPES_SUBSET = ["Phloem", "Xylem", "Procambium"]
#
# Example 3 — all cells:
#   CELL_TYPES_SUBSET = None

CELL_TYPES_SUBSET = ["Stomatal lineage", "Pavement cell", "Guard cell"]

# ── Create output folders ────────────────────────────────────
os.makedirs(BASE_DIR, exist_ok=True)

OUTPUT_DIR     = os.path.join(BASE_DIR, "figures")
OUTPUT_TABLES  = os.path.join(BASE_DIR, "tables")

os.makedirs(OUTPUT_DIR,    exist_ok=True)
os.makedirs(OUTPUT_TABLES, exist_ok=True)

sc.settings.figdir = OUTPUT_DIR

# ─────────────────────────────────────────────
# 1. LOAD OBJECT (generated by 01_single_cell.R)
# ─────────────────────────────────────────────

print("── 1. Loading AnnData ──")
Pc_esp = sc.read_h5ad(INPUT_H5AD)

# Recover embeddings exported from Seurat
# (export_to_scanpy() saves them as 'UMAP' and 'PCA')
Pc_esp.obsm['X_umap'] = Pc_esp.obsm['UMAP'].values
Pc_esp.obsm['X_pca']  = Pc_esp.obsm['PCA'].values

sc.set_figure_params(figsize=(10, 10), dpi=300, dpi_save=300)

print(Pc_esp)

# Reference UMAP colored by cell type
sc.pl.umap(
    Pc_esp,
    color=ANNOTATION_COL,
    show=False,
    save=f"_{ANNOTATION_COL}.png"
)

adata = Pc_esp  # alias para el resto del pipeline

# Verify annotation column exists
if ANNOTATION_COL not in adata.obs.columns:
    available = list(adata.obs.columns)
    raise ValueError(
        f"Columna '{ANNOTATION_COL}' no encontrada en obs.\n"
        f"Columnas disponibles: {available}"
    )

# ── Subset by cell types ─────────────────────────────────────
if CELL_TYPES_SUBSET is not None:
    tipos_disponibles = adata.obs[ANNOTATION_COL].unique().tolist()
    tipos_no_encontrados = [t for t in CELL_TYPES_SUBSET if t not in tipos_disponibles]

    if tipos_no_encontrados:
        print(f"⚠ Tipos celulares no encontrados: {tipos_no_encontrados}")
        print(f"  Tipos disponibles: {sorted(tipos_disponibles)}")

    adata = adata[adata.obs[ANNOTATION_COL].isin(CELL_TYPES_SUBSET)].copy()
    print(f"── Subset aplicado: {adata.n_obs:,} células conservadas")
    print(f"   Tipos incluidos: {CELL_TYPES_SUBSET}")

    # UMAP of subset for verification
    sc.pl.umap(
        adata,
        color=ANNOTATION_COL,
        title=f"Subset: {', '.join(CELL_TYPES_SUBSET)}",
        show=False,
        save=f"_subset_{'_'.join(CELL_TYPES_SUBSET)}.png".replace(" ", "_")
    )
else:
    print(f"── Sin subset: usando todas las células ({adata.n_obs:,})")

# ─────────────────────────────────────────────
# 2. PREPROCESSING
# ─────────────────────────────────────────────

print("── 2. Preprocessing ──")

# Usar reducción Harmony si está disponible, si no usar PCA
if "X_harmony" in adata.obsm:
    reduction_key = "X_harmony"
    print("   Using reduction: Harmony")
elif "X_pca" in adata.obsm:
    reduction_key = "X_pca"
    print("   Using reduction: PCA")
else:
    print("   Computing PCA from scratch...")
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    sc.pp.highly_variable_genes(adata, n_top_genes=2000)
    sc.pp.pca(adata, n_comps=N_PCS)
    reduction_key = "X_pca"

# Rebuild neighbor graph on available reduction
sc.pp.neighbors(adata, use_rep=reduction_key, n_neighbors=N_NEIGHBORS, random_state=RANDOM_SEED)

# Recompute UMAP if not present
if "X_umap" not in adata.obsm:
    print("   Computing UMAP...")
    sc.tl.umap(adata, random_state=RANDOM_SEED)

# ─────────────────────────────────────────────
# 3. INITIAL VISUALIZATION
# ─────────────────────────────────────────────

print("── 3. Reference UMAP ──")

sc.pl.umap(
    adata,
    color=ANNOTATION_COL,
    title="Tipos celulares",
    save="_cell_types.pdf",
    show=False
)

# ─────────────────────────────────────────────
# 4. PSEUDOTIME WITH PALANTIR
# ─────────────────────────────────────────────

print("── 4. Pseudotime with Palantir ──")

# Diffusion map (required by Palantir)
sc.tl.diffmap(adata, n_comps=10)

# Select root cell: closest cell to the centroid of the root cell type
root_cells = adata.obs.index[adata.obs[ANNOTATION_COL] == ROOT_CELL_TYPE]
if len(root_cells) == 0:
    raise ValueError(
        f"No se encontraron células de tipo '{ROOT_CELL_TYPE}' en '{ANNOTATION_COL}'.\n"
        f"Tipos disponibles: {adata.obs[ANNOTATION_COL].unique().tolist()}"
    )

# Use diffusion map centroid as root cell
dm_coords = adata.obsm["X_diffmap"][adata.obs[ANNOTATION_COL] == ROOT_CELL_TYPE]
centroid   = dm_coords.mean(axis=0)
dists      = np.linalg.norm(adata.obsm["X_diffmap"] - centroid, axis=1)
root_cell  = adata.obs.index[np.argmin(dists)]
print(f"   Célula raíz seleccionada: {root_cell}")

# Run Palantir
palantir_result = palantir.core.run_palantir(
    adata,
    early_cell=root_cell,
    use_early_cell_as_start=True,
    num_waypoints=500,
    n_jobs=4,
)

# Add pseudotime and entropy to the object
adata.obs["palantir_pseudotime"] = palantir_result.pseudotime
adata.obs["palantir_entropy"]    = palantir_result.entropy

# Plot pseudotime on UMAP
sc.pl.umap(
    adata,
    color=["palantir_pseudotime", "palantir_entropy"],
    cmap="viridis",
    save="_palantir_pseudotime.pdf",
    show=False
)

# ─────────────────────────────────────────────
# 5. TRAJECTORY TREE WITH scFates
# ─────────────────────────────────────────────

print("── 5. Trajectory tree with scFates ──")

# Learn principal tree on the diffusion map
scf.tl.tree(
    adata,
    method="ppt",           # Principal Progression Tree
    Nodes=20,               # number of tree nodes (adjust based on complexity)
    use_rep="X_diffmap",
    seed=RANDOM_SEED,
)

# Compute scFates pseudotime from root
scf.tl.pseudotime(
    adata,
    n_jobs=4,
    seed=RANDOM_SEED,
)

# Detect bifurcations
scf.tl.test_fork(adata, n_jobs=4)

# Plot tree on UMAP
scf.pl.graph(
    adata,
    basis="umap",
    color_cells=ANNOTATION_COL,
    save=f"{OUTPUT_DIR}/scfates_tree.pdf",
    show=False
)

# Plot scFates pseudotime
scf.pl.trajectory(
    adata,
    basis="umap",
    color_cells="t",   # 't' = pseudotime computed by scFates
    save=f"{OUTPUT_DIR}/scfates_pseudotime.pdf",
    show=False
)

# ─────────────────────────────────────────────
# 6. GENES ASSOCIATED WITH PSEUDOTIME
# ─────────────────────────────────────────────

print("── 6. Pseudotime-associated genes (scFates) ──")

# Gene ~ pseudotime association test (GAM)
scf.tl.test_association(
    adata,
    n_jobs=4,
    A_cut=0.5,    # Amplitud mínima de cambio
)

# Filter significant genes
sig_genes = adata.var[adata.var["signi"]].index.tolist()
print(f"   Genes significativos: {len(sig_genes)}")

# Save gene association table
assoc_df = adata.var[adata.var["signi"]].sort_values("A", ascending=False)
assoc_df.to_csv(f"{OUTPUT_DIR}/pseudotime_genes_associated.csv")

# Heatmap of significant genes along pseudotime
if len(sig_genes) > 0:
    top_genes = assoc_df.head(50).index.tolist()
    scf.pl.trends(
        adata,
        features=top_genes,
        save=f"{OUTPUT_DIR}/pseudotime_gene_trends.pdf",
        show=False
    )

# ─────────────────────────────────────────────
# 7. BIFURCATION GENES
# ─────────────────────────────────────────────

print("── 7. Differential genes at bifurcations ──")

# Only if bifurcations were detected
if "fork" in adata.uns:
    scf.tl.test_fork(adata, n_jobs=4)

    fork_genes = adata.var[adata.var["signi_fk"]].index.tolist()
    print(f"   Genes en bifurcación: {len(fork_genes)}")

    fork_df = adata.var[adata.var["signi_fk"]].sort_values("A_fk", ascending=False)
    fork_df.to_csv(f"{OUTPUT_DIR}/pseudotime_fork_genes.csv")

    if len(fork_genes) > 0:
        scf.pl.trends(
            adata,
            features=fork_df.head(30).index.tolist(),
            save=f"{OUTPUT_DIR}/fork_gene_trends.pdf",
            show=False
        )
else:
    print("   No bifurcations detected in the tree.")

# ─────────────────────────────────────────────
# 8. SAVE FINAL OBJECT
# ─────────────────────────────────────────────

print("── 8. Saving final object ──")

output_h5ad = f"{OUTPUT_DIR}/pbmc_pseudotime.h5ad"
adata.write_h5ad(output_h5ad)
print(f"   Guardado en: {output_h5ad}")

# ─────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────

print("\n══════════════════════════════════════")
print("  PSEUDOTIME COMPLETE")
print("══════════════════════════════════════")
print(f"  Input:              {INPUT_H5AD}")
print(f"  Output dir:         {OUTPUT_DIR}")
print(f"  Células analizadas: {adata.n_obs:,}")
print(f"  Genes totales:      {adata.n_vars:,}")
print(f"  Genes en pseudot.:  {len(sig_genes)}")
print(f"  Objeto final:       {output_h5ad}")
print("══════════════════════════════════════\n")
