# =============================================================================
# capitulo2_pseudobulk_de.R — Pseudobulk Differential Expression & GO (Part 2)
# =============================================================================
# Requires: pbmc_harmony_curated.rds generated by capitulo1_single_cell.R
# Covers pseudobulk DE (DESeq2), volcano plots, GO enrichment,
#         log2FC heatmaps, and network inference.
# =============================================================================

# ── Configuration (must match capitulo1_single_cell.R) ───────────────────────────────
PIPELINE_DIR <- "/workspace/ScRNASeq-Docker/workflow"
DATA_DIR     <- "/workspace/."
base_dir     <- file.path(DATA_DIR, "resultados")

source(file.path(PIPELINE_DIR, "load_libraries.R"))
source(file.path(PIPELINE_DIR, "custom_seurat.R"))
source(file.path(PIPELINE_DIR, "ScRNA_Analysis_Functions.R"))

list2env(create_pipeline_dirs(base_dir), envir = .GlobalEnv)  # creates output folders and loads their paths as variables

set.seed(1807)


# =============================================================================
# ████████████████████████  PART 2 — PSEUDOBULK DE & GO  ██████████████████████
# =============================================================================


# =============================================================================
# LOAD — CURATED OBJECT FROM PART 1
# =============================================================================
# Loads the final annotated object produced by capitulo1_single_cell.R.
# Make sure capitulo1_single_cell.R has been run and the checkpoint exists.

pbmc_harmony <- readRDS(file.path(dir_objects, "pbmc_harmony_curated.rds"))


# =============================================================================
# SECTION 14 — CELL-TYPE SUBSETS
# =============================================================================
# Creates one Seurat subset per curated cell type for downstream pseudobulk
# analysis. Object names are sanitised so they can be used safely as list names
# and output filenames.
#
# ┌─ SET THE ANNOTATION COLUMN TO USE FOR PART 2 ───────────────────────────────
#   pseudobulk_annot_col : metadata column containing the final cell-type labels
# └─────────────────────────────────────────────────────────────────────────────
pseudobulk_annot_col <- "celltype_curated"

# Create cell-type subsets for pseudobulk analysis
cell_type_subsets <- create_cell_type_subsets(pbmc_harmony, annot_col = pseudobulk_annot_col)


# =============================================================================

message("\n✓ SECTION 14 COMPLETE: Cell-type subsets created")
# SECTION 15 — PSEUDO-REPLICATE ASSIGNMENT
# =============================================================================
# Assigns random pseudo-replicates within each condition for every cell type.
# Only subsets containing at least two conditions are kept for Part 2.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   pseudobulk_conditions : NULL = use all conditions
#                           c("0N", "0.5N") = use only those two
#   n_pseudoreps          : pseudo-replicates per condition per cell type
# └─────────────────────────────────────────────────────────────────────────────
pseudobulk_conditions <- NULL   # change to e.g. c("0.5N", "5N") to subset
n_pseudoreps          <- 3

cell_type_subsets_replicates <- assign_pseudoreplicates_batch(cell_type_subsets,
                                                             pseudobulk_conditions = pseudobulk_conditions,
                                                             n_pseudoreps = n_pseudoreps)


# QC check — replace Pavement_Cell with any cell type name from your data:
table(cell_type_subsets_replicates$Pavement_Cell$replicate)
table(cell_type_subsets_replicates$Pavement_Cell$orig.ident)


# =============================================================================

message("\n✓ SECTION 15 COMPLETE: Pseudo-replicates assigned")
# SECTION 16 — PSEUDOBULK TABLES AND DESEQ2
# =============================================================================
# Aggregates counts by pseudo-replicate for each cell type, saves the resulting
# count tables, and runs DESeq2 for the user-defined pairwise contrasts.
#
# ┌─ DEFINE YOUR CONDITION CONTRASTS HERE ──────────────────────────────────────
#   comparisons : each entry must contain
#                   conds = c("reference", "treatment")
#                   tag   = output folder / file label
#
#   log2FC interpretation:
#     positive → gene is upregulated in treatment vs reference
#     negative → gene is upregulated in reference vs treatment
#
#   Example: conds = c("0.5N", "5N")  →  log2FC = log2(5N / 0.5N)
# └─────────────────────────────────────────────────────────────────────────────
comparisons <- list(
  list(conds = c("0.5N", "5N"), tag = "0.5N_vs_5N"),
  list(conds = c("0N",   "5N"), tag = "0N_vs_5N")
)

# ┌─ SELECT WHICH CELL TYPES TO ANALYZE ────────────────────────────────────────
#   NULL = analyze all cell types
#   c("Epidermis", "Cortex") = analyze only these
# └─────────────────────────────────────────────────────────────────────────────
cell_types_to_analyze <- NULL  # Change to c("Epidermis", "Cortex") to filter

output_dir <- dir_06

# Run pseudobulk aggregation and DESeq2 analysis
deseq2_results <- run_pseudobulk_deseq2_analysis(
  cell_type_subsets_replicates = cell_type_subsets_replicates,
  comparisons = comparisons,
  output_dir = output_dir,
  cell_types = cell_types_to_analyze,
  pseudobulk_dir = file.path(dir_objects, "pseudobulk_replicas")
)


# =============================================================================

message("\n✓ SECTION 16 COMPLETE: Pseudobulk aggregation and DESeq2 complete")
# SECTION 17 — VOLCANO PLOTS
# =============================================================================
# Renders one PNG volcano plot per cell type for a selected contrast and also
# combines them into a single PDF.
#
# ┌─ VOLCANO PARAMETERS ─────────────────────────────────────────────────────────
#   volcano_tag : tag of the contrast to visualize (must match comparisons)
#   padj_cut    : adjusted p-value threshold
#   lfc_cut     : absolute log2 fold-change threshold
# └─────────────────────────────────────────────────────────────────────────────
volcano_tag <- "0.5N_vs_5N"
padj_cut    <- 0.05
lfc_cut     <- 1

render_volcano_plots(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag, "volcano"),
  pdf_name    = paste0("VolcanoPlots_", volcano_tag, ".pdf"),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut
)


# =============================================================================

message("\n✓ SECTION 17 COMPLETE: Volcano plots saved")
# SECTION 18 — DIFFERENTIAL GENE TABLES
# =============================================================================
# Builds combined differential-expression summary tables for one selected
# contrast across all cell types.
#
# ┌─ DIFFERENTIAL TABLE PARAMETERS ──────────────────────────────────────────────
#   diff_prefix : output filename prefix for the discrete matrix
# └─────────────────────────────────────────────────────────────────────────────
diff_prefix <- paste0("diff_table_", volcano_tag)

diff_tables <- build_differential_tables(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  prefix      = diff_prefix
)


# =============================================================================

message("\n✓ SECTION 18 COMPLETE: Differential gene tables saved")
# SECTION 19 — GO ENRICHMENT (SIMPLE)
# =============================================================================
# Gene Ontology enrichment per cell type for the selected contrast.

# ┌─ CHANGE FOR YOUR ORGANISM ────────────────────────────────────────────────
#   Arabidopsis: go_orgdb = org.At.tair.db  |  go_keytype = "TAIR"
#   Human:       go_orgdb = org.Hs.eg.db    |  go_keytype = "ENSEMBL"
#   Mouse:       go_orgdb = org.Mm.eg.db    |  go_keytype = "ENSEMBL"
# └─────────────────────────────────────────────────────────────────────────
go_space    <- "BP"   # "MF" (function) or "CC" (component)
go_orgdb    <- org.At.tair.db
go_keytype  <- "TAIR"
padj_cutoff <- 0.05

deseq2_files <- list.files(file.path(dir_06, volcano_tag),
                           pattern = "^DESeq2_.*\\.csv$",
                           full.names = TRUE)

for (deseq2_file in deseq2_files) {
  cell_type <- gsub("^DESeq2_|\\.csv$", "", basename(deseq2_file))

  deseq2_results <- read.csv(deseq2_file, row.names = 1)
  sig_genes <- rownames(deseq2_results)[deseq2_results$padj < padj_cutoff]

  if (length(sig_genes) > 0) {
    run_simple_go_enrichment(
      diff_table = data.frame(gene_id = sig_genes),
      output_dir = file.path(dir_07, volcano_tag),
      orgdb        = go_orgdb,
      keytype      = go_keytype,
      go_space = go_space,
      padj_cutoff = padj_cutoff,
      cell_type = cell_type,
      contrast_tag = volcano_tag
    )
  }
}

# =============================================================================

message("\n✓ SECTION 19 COMPLETE: GO enrichment complete")
# SECTION 20 — LOG2FC HEATMAP
# =============================================================================
# Heatmap of log2FC values across all cell types for the selected contrast.
# Genes are ordered by the internal hierarchical dendrogram (cluster_rows = TRUE).
#
# ┌─ PARAMETERS ─────────────────────────────────────────────────────────────────
#   heatmap_limits : color scale range for log2FC values
# └─────────────────────────────────────────────────────────────────────────────
heatmap_limits <- c(-5, 5)

build_logfc_heatmap(
  logfc_table  = diff_tables$logfc,
  contrast_tag = volcano_tag,
  output_dir   = file.path(dir_06, volcano_tag),
  limits       = heatmap_limits
)


# =============================================================================

message("\n✓ SECTION 20 COMPLETE: Log2FC heatmap saved")
# SECTION 21 — COEXPRESSION NETWORK (hdWGCNA)
# =============================================================================
# Builds co-expression gene modules per cell type using hdWGCNA.
# Metacell aggregation handles single-cell sparsity before network construction.
# Outputs: modules TSV, hub genes TSV, eigengene PDF — one folder per cell type.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   cell_types_network : NULL = all cell types; or c("Guard Cell", "Mesophyll")
#   n_metacells        : metacells per group (default 25)
#   soft_power         : NULL = auto-detect; or integer to set manually
# └─────────────────────────────────────────────────────────────────────────────
cell_types_network <- NULL   # NULL = all, or e.g. c("Guard Cell", "Mesophyll")
n_metacells        <- 25
soft_power         <- NULL   # NULL = auto-detect

run_hdwgcna(
  seurat_obj  = pbmc_harmony,
  annot_col   = pseudobulk_annot_col,
  output_dir  = dir_08,
  cell_types  = cell_types_network,
  n_metacells = n_metacells,
  soft_power  = soft_power
)

message("\n✓ SECTION 21 COMPLETE: hdWGCNA co-expression networks saved")


# =============================================================================
# SECTION 22 — NETWORK EXPORT & VISUALIZATION
# =============================================================================
# Reads the hdWGCNA objects saved by Section 21 and for each cell type:
#   • Exports edges (source, target, weight) and nodes (gene, module, kME)
#   • Plots a co-expression network PDF coloured by module, sized by kME
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   tom_threshold      : minimum TOM weight to include an edge (lower = more edges)
#                        start at 0.1 and raise if the network is too dense
#   cell_types_network : NULL = all; or c("Guard Cell", "Mesophyll")
#   n_hub_label        : number of top hub genes to label in the plot
# └─────────────────────────────────────────────────────────────────────────────
tom_threshold      <- 0.1
cell_types_network <- NULL
n_hub_label        <- 5

plot_hdwgcna_network(
  hdwgcna_dir   = dir_08,
  output_dir    = dir_08,
  tom_threshold = tom_threshold,
  cell_types    = cell_types_network,
  n_hub_label   = n_hub_label
)

message("\n✓ SECTION 22 COMPLETE: Network files and plots saved")


# =============================================================================
# SECTION 23 — DE-FILTERED NETWORK
# =============================================================================
# Filters the co-expression network from Section 21 to only DE genes per
# cell type. Nodes are sized by |log2FC|, coloured by module, and the top
# hub genes / highest-FC genes are labelled.
# Reuses padj_cut and lfc_cut from Section 17.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   n_hub_label : number of top genes to label in the plot (default 10)
# └─────────────────────────────────────────────────────────────────────────────
n_hub_label <- 10

filter_hdwgcna_by_de(
  hdwgcna_dir = dir_08,
  de_dir      = file.path(dir_06, volcano_tag),
  output_dir  = dir_08,
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  n_hub_label = n_hub_label
)

message("\n✓ SECTION 23 COMPLETE: DE-filtered networks saved")




